//==========================================================================
//
// Character Animation Script     M U L T I P L A Y E R
//
//==========================================================================

//==========================================================================
// EVENTS
//
// format:
//
// <event description>
// {
//		[DEFAULT / <condition type> [<condition value>], ...]
//		{
//			<both/legs/torso> <animation> [sound <filename>]
//			<both/legs/torso> <animation> [sound <filename>]
//			...
//		}
// }
//
// legend:
//
// <event description>: pain, death, fireweapon, jump, jumpbk, land, dropweapon,
//		raiseweapon, reload, crouch_to_prone, shellshock, stunned
//		prone_to_crouch, meleeattack
//
//	NOTE: for gameplay anims (weapons firing, reload, etc) that show no legs movement
//		only the torso should animation from here, leave the legs doing what their
//		locomotive anims want them to do
//

EVENTS

fireweapon
{
// CLAW
	playerAnimType claw
	{
	}

// MANTLING
	movetype mantle
	{
	}

// MG42
	mounted mg42
	{
	}

// HOLD
	playerAnimType any_hold, movetype prone, playerAnimTypePrimary any_melee
	{
		torso mp_jug_maniac_prone_hold_throw
	}
	playerAnimType any_hold, movetype prone
	{
		torso pt_hold_prone_throw
	}
	playerAnimType any_hold, playerAnimTypePrimary any_melee
	{
		torso mp_jug_maniac_stand_hold_throw
	}
	playerAnimType any_hold
	{
		torso pt_hold_throw
	}

// PISTOLS AKIMBO
	akimbo, movetype idleprone2idle AND idleprone2idlecr AND idlecr2idleprone
	{
	}
	akimbo, movetype prone
	{
		torso mp_akimbo_prone_fire
	}
	akimbo, movetype moving MINUS slide2sprint
	{
	}
	akimbo, movetype crouching
	{
		torso mp_akimbo_crouch_fire
	}
	akimbo
	{
		torso mp_akimbo_stand_fire
	}

// PISTOLS
	playerAnimType pistol, movetype idleprone2idle AND idleprone2idlecr AND idlecr2idleprone
	{
	}
	playerAnimType pistol, movetype prone
	{
		torso pt_prone_shoot_pistol
	}
	playerAnimType pistol, movetype moving MINUS slide2sprint
	{
	}
	playerAnimType pistol, movetype crouching
	{
		torso pt_crouch_shoot_pistol
	}
	playerAnimType pistol
	{
		torso pt_stand_shoot_pistol
	}

// PROJECTILE WEAPONS (assume ads since you can't fire these from the hip)
	playerAnimType rocketlauncher, movetype idleprone
	{
		torso pt_prone_shoot_RPG
	}
	playerAnimType rocketlauncher, movetype moving
	{
		torso pt_stand_shoot_RPG
	}
	playerAnimType rocketlauncher, movetype crouching
	{
		torso pt_crouch_shoot_ads
	}
	playerAnimType rocketlauncher
	{
		torso pt_stand_shoot_RPG
	}

// MINIGUNS
	playerAnimType minigun, movetype idle
	{
		torso pt_mini_stand_shoot_auto
	}

	playerAnimType minigun
	{
	}

// MG & SMG
	weaponclass autofire, movetype idleprone2idle AND idleprone2idlecr AND idlecr2idleprone
	{
	}
	weaponclass autofire, movetype prone
	{
		torso pt_prone_shoot_auto
		duration 150
	}
	weaponclass autofire, movetype moving MINUS slide2sprint
	{
	}
	weaponclass autofire, movetype crouching
	{
		torso pt_crouch_shoot_auto
		duration 150
	}
	weaponclass autofire, weapon_position ads
	{
		torso mp_core_stand_fire_ADS
		duration 150
	}
	weaponclass autofire
	{
		torso pt_stand_shoot_auto
		duration 150
	}

// SHOTGUNS
	weaponclass spread, movetype idleprone2idle AND idleprone2idlecr AND idlecr2idleprone
	{
	}
	weaponclass spread, movetype prone
	{
		torso mp_prone_shotgun_fire 
	}
	weaponclass spread, movetype moving MINUS slide2sprint
	{
	}
	weaponclass spread, movetype crouching
	{
		torso mp_crouch_shotgun_fire
	}
	weaponclass spread, weapon_position ads
	{
		torso mp_core_stand_fire_ADS
	}
	weaponclass spread
	{
		torso mp_stand_shotgun_fire
	}

// DEFAULT (RIFLES)
	movetype idleprone2idle AND idleprone2idlecr AND idlecr2idleprone
	{
	}
	movetype prone
	{
		torso pt_prone_shoot_auto
	}
	movetype moving MINUS slide2sprint
	{
	}
	movetype crouching
	{
		torso pt_crouch_shoot
	}
	weapon_position ads
	{
		torso mp_core_stand_fire_ADS
	}

// SNIPER
	playerAnimType any_sniper
	{
		torso pt_rifle_fire
	}

// DEFAULT (RIFLES)
	default
	{
		torso pt_stand_shoot
	}
}

throw_grenade
{
	movetype prone, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_prone_grenade_throw
	}
	movetype prone, akimbo
	{
		torso mp_akimbo_prone_grenade_throw
	}
	movetype prone, playerAnimTypePrimary pistol
	{
		torso mp_pistol_prone_grenade_throw
	}
	movetype prone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_grenade_throw
	}
	movetype prone
	{
		torso mp_prone_grenade_throw_iw6
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_grenade_throw
	}
	movetype crouching, playerAnimTypePrimary pistol
	{
		torso mp_pistol_crouch_grenade_throw
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_grenade_throw
	}
	movetype crouching, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_crouch_grenade_throw
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_grenade_throw
	}
	movetype crouching
	{
		torso mp_crouch_grenade_throw
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_grenade_throw
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_grenade_throw
	}
	akimbo
	{
		torso mp_akimbo_stand_grenade_throw
	}
	playerAnimTypePrimary pistol
	{
		torso mp_pistol_stand_grenade_throw
	}
	playerAnimTypePrimary any_melee
	{
		torso jug_maniac_grenade_throw
	}
	default
	{
		torso mp_stand_grenade_throw
	}
}

throw_throwingknife
{
	movetype prone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_knife_throw 
	}
	movetype prone, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_prone_knife_throw
	}
	movetype prone, akimbo
	{
		torso mp_akimbo_prone_knife_throw 
	}
	movetype prone
	{
		torso pt_prone_throw_knife
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_knife_throw
	}
	movetype crouching, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_crouch_knife_throw
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_knife_throw
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_knife_throw
	}
	movetype crouching
	{
		torso pt_stand_throw_knife
	}
	akimbo
	{
		torso mp_akimbo_stand_knife_throw
	}
	playerAnimTypePrimary any_melee
	{
		torso jug_maniac_stand_knife_throw
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_knife_throw
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_knife_throw
	}
	default
	{
		torso pt_stand_throw_knife
	}
}

prepare_grenade sync preparegrenade_group
{
	movetype idleprone, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_prone_grenade_pull
	}
	movetype idleprone, akimbo
	{
		torso mp_akimbo_prone_grenade_pull
	}
	movetype idleprone, playerAnimTypePrimary pistol
	{
		torso mp_pistol_prone_grenade_pull
	}
	movetype idleprone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_grenade_hold
	}
	movetype idleprone
	{
		torso mp_prone_grenade_pull_iw6
	}
	movetype prone AND idleprone2idlecr AND prone2walkcr AND prone2walkcrbk
	{
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_grenade_pull
	}
	movetype crouching, playerAnimTypePrimary pistol
	{
		torso mp_pistol_crouch_grenade_pull
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_grenade_pullout
	}
	movetype crouching, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_crouch_grenade_load
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_grenade_hold
	}
	movetype crouching
	{
		torso mp_crouch_grenade_pull
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_grenade_hold
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_grenade_pullout
	}
	playerAnimTypePrimary any_melee
	{
		torso jug_maniac_grenade_hold
	}
	akimbo
	{
		torso mp_akimbo_stand_grenade_pull
	}
	playerAnimTypePrimary pistol
	{
		torso mp_pistol_stand_grenade_pull
	}
	default
	{
		torso mp_stand_grenade_pull
	}
}

prepare_throwingknife sync prepareknife_group
{
	movetype idleprone, akimbo
	{
		torso mp_akimbo_prone_knife_pull
	}
	movetype idleprone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_knife_pullout
	}
	movetype idleprone, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_prone_knife_pullout
	}
	movetype idleprone
	{
		torso pb_prone_pullout_knife
	}
	movetype prone AND idleprone2idlecr AND prone2walkcr AND prone2walkcrbk
	{
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_knife_pull
	}
	movetype crouching, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_crouch_knife_pullout
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_knife_pullout
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_knife_hold
	}
	movetype crouching
	{
		torso pb_stand_pullout_knife
	}
	akimbo
	{
		torso mp_akimbo_stand_knife_pull
	}
	playerAnimTypePrimary any_melee
	{
		torso jug_maniac_stand_knife_pullout
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_knife_pullout
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_knife_pullout
	}
	default
	{
		torso pb_stand_pullout_knife
	}
}

detonate
{
	movetype idleprone, playerAnimTypePrimary any_melee
	{
		torso mp_maniac_killstreak_launch_prone
	}
	movetype idleprone
	{
		torso mp_killstreak_launch_prone
	}
	movetype prone
	{
	}
	movetype crouching, playerAnimTypePrimary any_melee
	{
		torso mp_maniac_killstreak_launch_crouch
	}
	movetype crouching
	{
		torso mp_killstreak_launch_crouch
	}
	playerAnimTypePrimary any_melee
	{
		torso mp_maniac_killstreak_launch_stand
	}
	default
	{
		torso mp_killstreak_launch_stand
	}
}

meleeattack
{
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_melee duration 800
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_melee duration 800
	}
	movetype crouching, playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_crouch duration 800
	}
	playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_stand duration 800
	}
	movetype crouching, playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_crouch_melee_A
		torso jug_maniac_crouch_melee_B duration 800
		torso jug_maniac_crouch_melee_C duration 800
		torso jug_maniac_crouch_melee_D duration 800
		torso jug_maniac_crouch_melee_E duration 800
	}
	movetype prone, playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_prone_melee_A duration 800
		torso jug_maniac_prone_melee_B duration 800
	}
	playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_meleeA
		torso jug_maniac_meleeB duration 800
		torso jug_maniac_meleeC duration 800
		torso jug_maniac_meleeD duration 800
	}
	movetype prone
	{
		torso pt_melee_prone duration 800
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_melee duration 800
		torso mp_rpg_crouch_meleeA duration 800
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_melee duration 800
		torso mp_rpg_melee_swipe duration 800
	}
	movetype crouching
	{
		torso pt_melee_crouch_left2left duration 800
	}
	default
	{
		torso pt_melee_right2right_1 duration 400
		torso pt_melee_right2right_2 duration 400
	}
}

knife_melee
{
	movetype prone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_melee_A duration 800
		torso jug_maniac_prone_melee_B duration 800
	}
	movetype prone, akimbo
	{
		torso mp_akimbo_prone_melee_a blendtime 35 duration 800
	}
	movetype prone
	{
		torso mp_player_melee_3p_prone duration 800
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_melee duration 800
		torso mp_rpg_crouch_meleeA duration 800
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_melee duration 800
		torso mp_rpg_melee_swipe duration 800
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_melee duration 800
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_melee duration 800
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_melee_a blendtime 35 duration 800
	}
	movetype crouching, playerAnimTypePrimary pistol
	{
		torso mp_pistol_crouch_melee_A blendtime 35 duration 800
	}
	akimbo
	{
		torso mp_akimbo_stand_melee_A blendtime 35 duration 800
	}
	playerAnimTypePrimary pistol
	{
		torso mp_pistol_stand_melee_A blendtime 35 duration 800
	}
	movetype crouching, playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_crouch duration 800
	}
	playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_stand duration 800
	}
	movetype crouching, playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_crouch_melee_A
		torso jug_maniac_crouch_melee_B duration 800
		torso jug_maniac_crouch_melee_C duration 800
		torso jug_maniac_crouch_melee_D duration 800
		torso jug_maniac_crouch_melee_E duration 800
	}
	playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_meleeA
		torso jug_maniac_meleeB duration 800
		torso jug_maniac_meleeC duration 800
		torso jug_maniac_meleeD duration 800
	}
	default
	{
		torso pt_melee_pistol_1 duration 800
	}
}

knife_melee_charge_high
{
	movetype prone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_melee_A duration 800
		torso jug_maniac_prone_melee_B duration 800
	}
	movetype prone, akimbo
	{
		torso mp_akimbo_prone_melee_a blendtime 35 duration 800
	}
	movetype prone
	{
		torso mp_player_melee_3p_prone duration 800
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_melee duration 800
		torso mp_rpg_crouch_meleeA duration 800
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_melee duration 800
		torso mp_rpg_melee_swipe duration 800
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_melee duration 800
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_melee duration 800
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_melee_a blendtime 35 duration 800
	}
	movetype crouching, playerAnimTypePrimary pistol
	{
		torso mp_pistol_crouch_melee_A blendtime 35 duration 800
	}
	akimbo
	{
		torso mp_akimbo_stand_melee_A blendtime 35 duration 800
	}
	playerAnimTypePrimary pistol
	{
		torso mp_pistol_stand_melee_A blendtime 35 duration 800
	}
	movetype crouching, playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_crouch duration 800
	}
	playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_stand duration 800
	}
	movetype crouching, playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_crouch_melee_A
		torso jug_maniac_crouch_melee_B duration 800
		torso jug_maniac_crouch_melee_C duration 800
		torso jug_maniac_crouch_melee_D duration 800
		torso jug_maniac_crouch_melee_E duration 800
	}
	playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_meleeA
		torso jug_maniac_meleeB duration 800
		torso jug_maniac_meleeC duration 800
	}
	default
	{
		torso mp_player_melee_3p_stand_upper knife_in_right_hand duration 800
	}
}

knife_melee_charge_low
{
	movetype prone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_melee_A duration 800
		torso jug_maniac_prone_melee_B duration 800
	}
	movetype prone, akimbo
	{
		torso mp_akimbo_prone_melee_a blendtime 35 duration 800
	}
	movetype prone
	{
		torso mp_player_melee_3p_prone duration 800
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_melee duration 800
		torso mp_rpg_crouch_meleeA duration 800
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_melee duration 800
		torso mp_rpg_melee_swipe duration 800
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_melee duration 800
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_melee duration 800
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_melee_a blendtime 35 duration 800
	}
	movetype crouching, playerAnimTypePrimary pistol
	{
		torso mp_pistol_crouch_melee_A blendtime 35 duration 800
	}
	akimbo
	{
		torso mp_akimbo_stand_melee_A blendtime 35 duration 800
	}
	playerAnimTypePrimary pistol
	{
		torso mp_pistol_stand_melee_A blendtime 35 duration 800
	}
	movetype crouching, playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_crouch duration 800
	}
	playerAnimTypePrimary claw
	{
		torso mp_predator_swipe_stand duration 800
	}
	movetype crouching, playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_crouch_melee_A
		torso jug_maniac_crouch_melee_B duration 800
		torso jug_maniac_crouch_melee_C duration 800
		torso jug_maniac_crouch_melee_D duration 800
		torso jug_maniac_crouch_melee_E duration 800
	}
	playerAnimTypePrimary juggernautmaniac
	{
		torso jug_maniac_meleeD duration 800
	}
	default
	{
		torso mp_player_melee_3p_stand_lower knife_in_right_hand duration 800
	}
}

dropweapon
{
	nextweapon briefcase, movetype prone
	{
		both mp_bomb_prone_2_idle
	}
	nextweapon briefcase, movetype crouching
	{
		both mp_bomb_crouch_2_idle
	}
	nextweapon briefcase
	{
		both mp_bomb_stand_2_idle
	}
	playerAnimTypePrimary briefcase, movetype prone
	{
		both mp_bomb_prone_idle_2_prone
	}
	playerAnimTypePrimary briefcase, movetype crouching
	{
		both mp_bomb_crouch_idle_2_crouch
	}
	playerAnimTypePrimary briefcase
	{
		both mp_bomb_stand_idle_2_stand
	}
	nextweapon drill
	{
		torso mp_alien_drill_pickup
	}
	movetype idleprone, playerAnimTypePrimary grenade, nextweapon any_melee AND none
	{
		torso mp_maniac_killstreak_launch_prone duration 400 // using mp_maniac_killstreak_launch anims to cover up left-arm staying out when switching away from a primary grenade (AKA care package marker)
	}
	movetype NOT prone, playerAnimTypePrimary grenade, nextweapon any_melee AND none
	{
		torso mp_maniac_killstreak_launch_stand duration 400 // using mp_maniac_killstreak_launch anims to cover up left-arm staying out when switching away from a primary grenade (AKA care package marker)
	}
	nextweapon any_melee AND none
	{
	}
	playerAnimType briefcase AND laptop AND dogwhistle AND killstreaktrigger AND none
	{
	}
	playerAnimTypePrimary any_melee, nextweapon all MINUS dogwhistle MINUS killstreaktrigger
	{
	}
	movetype idleprone, playerAnimTypePrimary pistol, nextweapon dogwhistle
	{
		torso mp_whistle_pistol_prone
	}
	movetype idleprone, nextweapon dogwhistle
	{
		torso mp_whistle_prone
	}
	movetype idleprone, playerAnimTypePrimary any_melee, nextweapon killstreaktrigger
	{
		torso mp_maniac_killstreak_launch_prone
	}
	movetype idleprone, nextweapon killstreaktrigger
	{
		torso mp_killstreak_launch_prone
	}
	movetype idleprone, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_prone_weapon_switch
	}
	movetype idleprone, nextweapon rocketlauncher
	{
		torso mp_rpg_prone_weapon_switch
	}
	movetype idleprone, nextweapon_akimbo
	{
		torso mp_akimbo_prone_wpnswp_lg2pistol
	}
	movetype idleprone, akimbo, nextweapon pistol
	{
		torso mp_akimbo_prone_swap_akimbo2pstl
	}
	movetype idleprone, akimbo
	{
		torso mp_akimbo_prone_wpnswp_pistol2lg
	}
	movetype idleprone, playerAnimTypePrimary pistol
	{
		torso mp_prone_weapon_swap_pistol2lg
	}
	movetype idleprone, nextweapon pistol
	{
		torso mp_prone_weapon_swap_lg2pistol
	}
	movetype idleprone
	{
		torso mp_prone_weapon_switch_iw6
	}
	movetype prone
	{
	}
	movetype crouching, playerAnimTypePrimary pistol, nextweapon dogwhistle
	{
		torso mp_whistle_pistol_crouch
	}
	movetype crouching, nextweapon dogwhistle
	{
		torso mp_whistle_crouch
	}
	movetype crouching, playerAnimTypePrimary juggernautmaniac, nextweapon killstreaktrigger
	{
		torso mp_maniac_killstreak_launch_crouch
	}
	movetype crouching, nextweapon killstreaktrigger
	{
		torso mp_killstreak_launch_crouch
	}
	movetype crouching, playerAnimTypePrimary riotshield, nextweapon pistol
	{
		torso mp_shield_crouch_shield_2_pistol
	}
	movetype crouching, playerAnimTypePrimary riotshield, nextweapon rocketlauncher
	{
		torso mp_shield_crouch_wpnswp_shld2rpg
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_wpnswp_shld2gn
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher, nextweapon riotshield
	{
		torso mp_rpg_crouch_wpnswp_rpg2shld
	}
	movetype crouching, nextweapon riotshield
	{
		torso mp_shield_crouch_wpnswp_gn2shld
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_weapon_swap
	}
	movetype crouching, nextweapon rocketlauncher
	{
		torso mp_rpg_crouch_weapon_swap
	}
	movetype crouching, nextweapon_akimbo
	{
		torso mp_akimbo_crouch_wpnswp_lg2pistol
	}
	movetype crouching, akimbo, nextweapon pistol
	{
		torso mp_akimbo_crouch_swap_akimbo2pstl
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_wpnswp_pistol2lg
	}
	movetype crouching, playerAnimTypePrimary pistol
	{
		torso mp_crouch_weapon_swap_pistol2lg
	}
	movetype crouching, nextweapon pistol
	{
		torso mp_crouch_weapon_swap_lg2pistol
	}
	movetype crouching
	{
		torso mp_crouch_weapon_swap_iw6
	}
	playerAnimTypePrimary pistol, nextweapon dogwhistle
	{
		torso mp_whistle_pistol_stand
	}
	nextweapon dogwhistle
	{
		torso mp_whistle_stand
	}
	playerAnimTypePrimary juggernautmaniac, nextweapon killstreaktrigger
	{
		torso mp_maniac_killstreak_launch_stand
	}
	nextweapon killstreaktrigger
	{
		torso mp_killstreak_launch_stand
	}
	playerAnimTypePrimary riotshield, nextweapon rocketlauncher
	{
		torso mp_shield_stand_wpnswp_shld2rpg
	}
	playerAnimTypePrimary riotshield, nextweapon pistol
	{
		torso mp_shield_stand_shield_2_pistol
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_stand_wpnswp_shld2gn
	}
	playerAnimTypePrimary rocketlauncher, nextweapon riotshield
	{
		torso mp_rpg_stand_wpnswp_rpg2shld
	}
	nextweapon riotshield
	{
		torso mp_shield_stand_wpnswp_gn2shld
	}
	movetype laststand
	{
		torso pt_laststand_pullout_pose
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_weapon_swap
	}
	nextweapon rocketlauncher
	{
		torso mp_rpg_weapon_swap
	}
	nextweapon_akimbo
	{
		torso mp_akimbo_stand_wpn_swp_lg2ak
	}
	akimbo, nextweapon pistol
	{
		torso mp_akimbo_stand_swap_akimbo2pstl
	}
	akimbo
	{
		torso mp_akimbo_stand_swap_akimbo2lg
	}
	nextweapon minigun
	{
		torso mp_stand_weapon_swap_pistol2mini
	}
	playerAnimTypePrimary pistol
	{
		torso mp_stand_weapon_swap_pistol2lg
	}
	playerAnimTypePrimary minigun
	{
		torso mp_stand_weapon_swap_mini2pistol
	}
	nextweapon pistol
	{
		torso mp_stand_weapon_swap_lg2pistol
	}
	default
	{
		torso pt_stand_core_pullout
	}
}

raiseweapon
{
	// (Boon 07-11-2003) Don't want anything here - just blend into the correct pose.
}

reload
{
	playerAnimTypePrimary laptop AND any_melee
	{
	}
	akimbo, movetype idleprone2idlecr AND idleprone2idle
	{
		// fullbody reloads (like mp_akimbo_prone_reload) look terrible when they blend over to torso reloads (like mp_akimbo_crouch_reload)
	}
	akimbo, movetype idleprone
	{
		torso mp_akimbo_prone_reload
	}
	akimbo, movetype prone
	{
	}
	akimbo, movetype crouching
	{
		torso mp_akimbo_crouch_reload
	}
	akimbo
	{
		torso mp_akimbo_stand_reload
	}
	playerAnimTypePrimary pistol, movetype idleprone2idlecr AND idleprone2idle
	{
		// fullbody reloads (like mp_pistol_prone_reload) look terrible when they blend over to torso reloads (like mp_pistol_crouch_reload)
	}
	playerAnimTypePrimary pistol, movetype idleprone
	{
		torso mp_pistol_prone_reload
	}
	playerAnimTypePrimary pistol, movetype prone
	{
	}
	playerAnimTypePrimary pistol, movetype crouching
	{
		torso mp_pistol_crouch_reload
	}
	playerAnimTypePrimary pistol
	{
		torso mp_pistol_stand_reload
	}
	playerAnimTypePrimary rocketlauncher, movetype idleprone2idlecr AND idleprone2idle
	{
		// fullbody reloads (like mp_rpg_prone_reload) look terrible when they blend over to torso reloads (like mp_rpg_crouch_reload)
	}
	playerAnimTypePrimary rocketlauncher, movetype idleprone
 	{
	   	torso mp_rpg_prone_reload
	}
	playerAnimTypePrimary rocketlauncher, movetype prone
 	{
	}
	playerAnimTypePrimary rocketlauncher, movetype crouching
	{
		torso mp_rpg_crouch_reload
	}
	playerAnimTypePrimary rocketlauncher
 	{
	   	torso mp_rpg_reload
	}
	playerAnimTypePrimary any_bullpup, movetype idleprone
	{
		torso mp_prone_bullpup_reload
	}
	playerAnimTypePrimary any_bullpup, movetype prone
	{
	}
	playerAnimTypePrimary any_bullpup, movetype crouching
	{
		torso mp_crouch_bullpup_reload
	}
	playerAnimTypePrimary any_bullpup
	{
		torso mp_stand_bullpup_reload
	}
	weaponclass spread, movetype idleprone
	{
		torso mp_prone_shotgun_reload
	}
	weaponclass spread, movetype prone
	{
	}
	weaponclass spread, movetype idlecr AND idleprone2idlecr
	{
		torso mp_crouch_shotgun_reload
	}
	weaponclass spread, movetype crouching
	{
		torso pt_reload_crouchwalk
	}
	weaponclass spread
	{
		torso mp_stand_shotgun_reload
	}
	movetype idleprone2idlecr AND idleprone2idle
	{
		// fullbody reloads (like mp_prone_reload_iw6) look terrible when they blend over to torso reloads (like mp_crouch_reload)
	}
	movetype idleprone
	{
		torso mp_prone_reload_iw6
	}
	movetype prone
	{
	}
	movetype idlecr AND idleprone2idlecr
	{
		torso mp_crouch_reload
	}
	movetype crouching
	{
		torso pt_reload_crouchwalk
	}
	default
	{
		torso mp_stand_reload
	}
}

jump
{
	movetype run, playerAnimType any_hold
	{
		both mp_hold_runjump_takeoff
		duration 5
		blendtime 100
		aim idle_hold_aims
	}
	movetype run, akimbo
	{
		both runjump_takeoff_Akimbo
		duration 5
		blendtime 100
		aim idle_akimbo_aims
	}
	movetype run, playerAnimTypePrimary pistol
	{
		both runjump_takeoff_Pistol
		duration 5
		blendtime 100
		aim idle_pistol_aims
	}
	movetype run, playerAnimTypePrimary any_melee
	{
		both runjump_takeoff_JugManiac
		duration 5
		blendtime 100
		aim idle_maniac_aims
	}
	movetype run, playerAnimTypePrimary rocketlauncher
	{
		both runjump_takeoff_RPG
		duration 5
		blendtime 100
		aim idle_rocket_aims
	}
	movetype run, playerAnimTypePrimary riotshield
	{
		both mp_shield_runjump_takeoff
		duration 5
		blendtime 100
		aim idle_shield_aims
	}
	movetype run
	{
		both pb_runjump_takeoff
		duration 5
		blendtime 100
		aim idle_rifle_aims
	}
	playerAnimType any_hold
	{
		both mp_hold_standjump_takeoff
		duration 5
		blendtime 100
		aim idle_hold_aims
	}
	akimbo
	{
		both standjump_takeoff_Akimbo
		duration 5
		blendtime 100
		aim idle_akimbo_aims
	}
	playerAnimTypePrimary pistol
	{
		both standjump_takeoff_Pistol
		duration 5
		blendtime 100
		aim idle_pistol_aims
	}
	playerAnimTypePrimary any_melee
	{
		both standjump_takeoff_JugManiac
		duration 5
		blendtime 100
		aim idle_maniac_aims
	}
	playerAnimTypePrimary rocketlauncher
	{
		both standjump_takeoff_Rpg
		duration 5
		blendtime 100
		aim idle_rocket_aims
	}
	playerAnimTypePrimary riotshield
	{
		both mp_shield_standjump_takeoff
		duration 5
		blendtime 100
		aim idle_shield_aims
	}
	default
	{
		both pb_standjump_takeoff
		duration 5
		blendtime 100
		aim idle_rifle_aims
	}
}

jumpbk
{
	movetype crouching AND prone
	{
	}
	playerAnimType any_hold
	{
		both mp_hold_standjump_takeoff
		duration 5
		blendtime 100
		aim idle_hold_aims
	}
	akimbo
	{
		both standjump_takeoff_Akimbo
		duration 5
		blendtime 100
		aim idle_akimbo_aims
	}
	playerAnimTypePrimary pistol
	{
		both standjump_takeoff_Pistol
		duration 5
		blendtime 100
		aim idle_pistol_aims
	}
	playerAnimTypePrimary any_melee
	{
		both standjump_takeoff_JugManiac
		duration 5
		blendtime 100
		aim idle_maniac_aims
	}
	playerAnimTypePrimary rocketlauncher
	{
		both standjump_takeoff_Rpg
		duration 5
		blendtime 100
		aim idle_rocket_aims
	}
	playerAnimTypePrimary riotshield
	{
		both mp_shield_standjump_takeoff
		duration 5
		blendtime 100
		aim idle_shield_aims
	}
	default
	{
		both pb_standjump_takeoff
		duration 5
		blendtime 100
		aim idle_rifle_aims
	}
}

land
{
	movetype run, playerAnimType any_hold
	{
		both mp_hold_runjump_land
		duration 100
		blendtime 50
		aim idle_hold_aims
	}
	movetype run, akimbo
	{
		both runjump_land_Akimbo
		duration 100
		blendtime 50
		aim idle_akimbo_aims
	}
	movetype run, playerAnimTypePrimary pistol
	{
		both runjump_land_Pistol
		duration 100
		blendtime 50
		aim idle_pistol_aims
	}
	movetype run, playerAnimTypePrimary any_melee
	{
		both runjump_land_JugManiac
		duration 100
		blendtime 50
		aim idle_maniac_aims
	}
	movetype run, playerAnimTypePrimary rocketlauncher
	{
		both runjump_land_RPG
		duration 100
		blendtime 50
		aim idle_rocket_aims
	}
	movetype run, playerAnimTypePrimary riotshield
	{
		both mp_shield_runjump_land
		duration 100
		blendtime 50
		aim idle_shield_aims
	}
	movetype run
	{
		both pb_runjump_land
		duration 100
		blendtime 50
		aim idle_rifle_aims
	}
	playerAnimType any_hold
	{
		both mp_hold_standjump_land
		duration 100
		blendtime 50
		aim idle_hold_aims
	}
	akimbo
	{
		both standjump_land_Akimbo
		duration 100
		blendtime 50
		aim idle_akimbo_aims
	}
	playerAnimTypePrimary pistol
	{
		both standjump_land_Pistol
		duration 100
		blendtime 50
		aim idle_pistol_aims
	}
	playerAnimTypePrimary any_melee
	{
		both standjump_land_JugManiac
		duration 100
		blendtime 50
		aim idle_maniac_aims
	}
	playerAnimTypePrimary rocketlauncher
	{
		both standjump_land_Rpg
		duration 100
		blendtime 50
		aim idle_rocket_aims
	}
	playerAnimTypePrimary riotshield
	{
		both mp_shield_standjump_land
		duration 100
		blendtime 50
		aim idle_shield_aims
	}
	default
	{
		both pb_standjump_land
		duration 100
		blendtime 50
		aim idle_rifle_aims
	}
}

shellshock
{
	movetype laststand
	{
	}
	movetype prone, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_prone_flashreaction duration 5000 blendtime 50
	}
	movetype prone
	{
		torso mp_prone_flash_reaction duration 5000 blendtime 50
	}
	movetype crouching, akimbo
	{
		torso mp_akimbo_crouch_flash_reaction_a duration 5000 blendtime 50
		torso mp_akimbo_crouch_flash_reaction_b duration 5000 blendtime 50
	}
	movetype idlecr, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_flash duration 5000 blendtime 50
	}
	movetype crouching, playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_walk_flash duration 5000 blendtime 50
	}
	movetype crouching, playerAnimTypePrimary any_melee
	{
		torso jug_maniac_crouch_flashreaction duration 5000 blendtime 50
	}
	movetype crouching, playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_crouch_flash duration 5000 blendtime 50
	}
	movetype crouching, playerAnimTypePrimary pistol
	{
		torso mp_pistol_crouch_flash_reaction_A duration 5000 blendtime 50
		torso mp_pistol_crouch_flash_reaction_B duration 5000 blendtime 50
	}
	movetype crouching
	{
		torso mp_crouch_flash_reaction_A duration 5000 blendtime 50
		torso mp_crouch_flash_reaction_B duration 5000 blendtime 50
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_crouch_flash duration 5000 blendtime 50
	}
	akimbo
	{
		torso mp_akimbo_stand_flash_reaction_A duration 5000 blendtime 50
		torso mp_akimbo_stand_flash_reaction_B duration 5000 blendtime 50
	}
	playerAnimTypePrimary any_melee
	{
		torso jug_maniac_flash_reactionA duration 5000 blendtime 50
		torso jug_maniac_flash_reactionB duration 5000 blendtime 50
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_flash duration 5000 blendtime 50
	}
	playerAnimTypePrimary pistol
	{
		torso mp_pistol_stand_flash_reaction_A duration 5000 blendtime 50
		torso mp_pistol_stand_flash_reaction_B duration 5000 blendtime 50
	}
	default
	{
		torso mp_stand_flash_reaction duration 5000 blendtime 50
		torso mp_stand_flash_reaction_B duration 5000 blendtime 50
	}
}

death
{
	damagetype damage_melee_dog, hitdirection hit_front
	{
		both iw6_dog_kill_front_quick_guy_1_mp
	}
	damagetype damage_melee_dog, hitdirection hit_back
	{
		both iw6_dog_kill_back_quick_guy_1_mp
	}
	damagetype damage_melee_dog, hitdirection hit_left
	{
		both iw6_dog_kill_left_quick_guy_1_mp
	}
	damagetype damage_melee_dog, hitdirection hit_right
	{
		both iw6_dog_kill_right_quick_guy_1_mp
	}
	crouching damagetype damage_melee, hitdirection hit_front
	{
		both mp_melee_death_crouch_F
		local_melee_victim pb_melee_death_crouching_front
	}
	crouching damagetype damage_melee, hitdirection hit_back
	{
		both mp_melee_death_crouch_B
		local_melee_victim pb_melee_death_crouching_back
	}
	crouching damagetype damage_melee, hitdirection hit_left
	{
		both mp_melee_death_crouch_L
		local_melee_victim pb_melee_death_crouching_left
	}
	crouching damagetype damage_melee, hitdirection hit_right
	{
		both mp_melee_death_crouch_R
		local_melee_victim pb_melee_death_crouching_right
	}
	movetype prone
	{
		both pb_prone_death_quickdeath
	}
	damagetype damage_melee, hitdirection hit_front
	{
		both mp_melee_death_stand_F
		synchronized
		local_melee_victim pb_melee_death_standing_front
	}
	damagetype damage_melee, hitdirection hit_back
	{
		both mp_melee_death_stand_B
		synchronized
		local_melee_victim pb_melee_death_standing_back
	}
	damagetype damage_melee, hitdirection hit_left
	{
		both mp_melee_death_stand_L
		synchronized
		local_melee_victim pb_melee_death_standing_left
	}
	damagetype damage_melee, hitdirection hit_right
	{
		both mp_melee_death_stand_R
		synchronized
		local_melee_victim pb_melee_death_standing_right
	}
	movetype laststand
	{
		both pb_laststand_death
	}
	movetype idlecr
	{
		both pb_crouch_death_headshot_front
		both pb_crouch_death_clutchchest
		both pb_crouch_death_flip
		both pb_crouch_death_fetal
		both pb_crouch_death_falltohands
	}
	damagetype damage_explosion, hitdirection hit_front
	{
		both pb_shotgun_death_back2
	}
	damagetype damage_explosion, hitdirection hit_left
	{
		both pb_shotgun_death_spinL
	}
	damagetype damage_explosion, hitdirection hit_right
	{
		both pb_shotgun_death_spinR
	}
	damagetype damage_explosion, hitdirection hit_back
	{
		both pb_explosion_death_F1
	}
	damagetype damage_explosion_light, hitlocation hit_legs, hitdirection hit_front
	{
		both pb_shotgun_death_legs
	}
	damagetype damage_explosion_light, hitdirection hit_front
	{
		both pb_shotgun_death_back2
		both pb_stand_death_chest_blowback
	}
	damagetype damage_explosion_light, hitdirection hit_left
	{
		both pb_shotgun_death_spinL
	}
	damagetype damage_explosion_light, hitdirection hit_right
	{
		both pb_shotgun_death_spinR
	}
	damagetype damage_explosion_light, hitdirection hit_back
	{
		both pb_shotgun_death_front
	}
	movetype runbk
	{
		both pb_death_run_back
	}
	movetype run AND runcr, strafing left
	{
		both pb_death_run_left
	}
	movetype run AND runcr, strafing right
	{
		both pb_death_run_right
	}
	movetype runcr
	{
		both pb_crouchrun_death_drop
		both pb_crouchrun_death_crumple
	}
	movetype run
	{
		both pb_death_run_forward_crumple
		both pb_death_run_onfront
		both pb_death_run_stumble
	}
	hitlocation hit_head
	{
		both pb_stand_death_neckdeath
		both pb_stand_death_neckdeath_thrash
		both pb_stand_death_head_straight_back
		both pb_stand_death_head_collapse
		both pb_stand_death_tumbleback
		both pb_stand_death_leg_kickup
		both pb_stand_death_headshot_slowfall
		both pb_stand_death_lowerback
		both pb_stand_death_nervedeath
		both pb_stand_death_headchest_topple
		both pb_stand_death_chest_spin
	}
	hitlocation hit_neck
	{
		both pb_stand_death_neckdeath
		both pb_stand_death_neckdeath_thrash
	}
	default
	{
		both pb_stand_death_frontspin
		both pb_stand_death_legs
		both pb_stand_death_lowerback
		both pb_stand_death_chest_spin
		both pb_stand_death_shoulder_stumble
		both pb_stand_death_chest_blowback
		both pb_stand_death_tumbleback
		both pb_stand_death_kickup
		both pb_stand_death_stumbleforward
		both pb_stand_death_leg
		both pb_stand_death_shoulderback
	}
}

rocket_corpse
{
	default 
	{
		both mp_rpg_death_long blendtime 1
	}
}

flinch
{
	movetype laststand
	{
	}
	playerAnimTypePrimary any_melee, movetype idleprone
	{
		torso jug_maniac_prone_flinch_A
		torso jug_maniac_prone_flinch_B
		torso jug_maniac_prone_flinch_C
	}
	playerAnimTypePrimary rocketlauncher, movetype idleprone
	{
		torso mp_rpg_prone_flinch_A
		torso mp_rpg_prone_flinch_B
		torso mp_rpg_prone_flinch_C
	}
	akimbo, movetype idleprone
	{
		torso mp_flinch_akimbo_prone_A
		torso mp_flinch_akimbo_prone_B
	}
	playerAnimTypePrimary pistol, movetype idleprone
	{
		torso mp_flinch_pistol_prone_A
		torso mp_flinch_pistol_prone_B
	}
	movetype idleprone
	{
		torso mp_flinch_prone_A
		torso mp_flinch_prone_B
		torso mp_flinch_prone_C
	}
	movetype prone
	{
	}
	playerAnimTypePrimary riotshield, movetype idlecr
	{
		torso mp_shield_flinch_crouch_A
		torso mp_shield_flinch_crouch_B
	}
	playerAnimTypePrimary riotshield, movetype crouching
	{
		torso mp_shield_flinch_crouch_C
	}
	playerAnimTypePrimary any_melee, movetype crouching
	{
		torso jug_maniac_crouch_flinch_A
		torso jug_maniac_crouch_flinch_B
		torso jug_maniac_crouch_flinch_C
	}
	playerAnimTypePrimary rocketlauncher, movetype crouching
	{
		torso mp_rpg_crouch_flinch_A
		torso mp_rpg_crouch_flinch_B
		torso mp_rpg_crouch_flinch_C
	}
	akimbo, movetype crouching
	{
		torso mp_flinch_akimbo_crouch_A
		torso mp_flinch_akimbo_crouch_B
		torso mp_flinch_akimbo_crouch_C
	}
	playerAnimTypePrimary pistol, movetype crouching
	{
		torso mp_flinch_pistol_crouch_A
		torso mp_flinch_pistol_crouch_B
		torso mp_flinch_pistol_crouch_C
	}
	movetype crouching
	{
		torso mp_flinch_crouch_A
		torso mp_flinch_crouch_B
		torso mp_flinch_crouch_C
	}
	playerAnimTypePrimary riotshield
	{
		torso mp_shield_flinch_stand_A
		torso mp_shield_flinch_stand_B
	}
	playerAnimTypePrimary any_melee
	{
		torso jug_maniac_stand_flinch_A
		torso jug_maniac_stand_flinch_B
		torso jug_maniac_stand_flinch_C
	}
	playerAnimTypePrimary rocketlauncher
	{
		torso mp_rpg_stand_flinch_A
		torso mp_rpg_stand_flinch_B
		torso mp_rpg_stand_flinch_C
	}
	akimbo
	{
		torso mp_flinch_akimbo_stand_A
		torso mp_flinch_akimbo_stand_B
	}
	playerAnimTypePrimary pistol
	{
		torso mp_flinch_pistol_stand_A
		torso mp_flinch_pistol_stand_B
	}
	default
	{
		torso mp_flinch_stand_A
		torso mp_flinch_stand_B
		torso mp_flinch_stand_C
	}
}

pullout_trophysystem
{
	movetype prone
	{
		torso mp_pullout_trophysystem_prone blendtime 1
	}
	default
	{
		torso mp_pullout_trophysystem blendtime 1
	}
}

enter_last_stand
{
	default
	{
		torso mp_predator_suicide_detonate
	}
}